spring.application.name=coreris
#server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ris_db?options=-c%20timezone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=postgres

# Show SQL queries in the console (Critical for debugging and performance tuning)
spring.jpa.show-sql=true
# Format SQL queries to be readable
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=create-drop

#JWT Configuration

security.jwt.secret-key = dlgsbisuhfowlchdiouvfdfhgwvfgwufgvwuyefheygfjweyfyefujehfueygfuwegfkifgegfqkey fg
security.jwt.expiration-time = 86400000